@startuml
class Metadata {
    name : String
    description : String
    created : timestamp
    last_updated : timestamp
    created_by : String
    annotations : list
    add_annotation(obj)
    remove_annotation(name)
    get_annotation(name)
    to_json()
    to_pickle()
}
note right: Metadata is intended\nto be stored with a dataset.\nIt will be a collection of\ndataset descriptive/\nstructural metadata and annotations.

abstract class Annotation {
    type : String
    name : String
    created : timestamp
    last_updated : timestamp
    set_last_updated()
    to_json()
    to_pickle()
}
note right: Annotation types that can be\n added to the metadata

class LabelAnnotation {
    label : String
    value : String
}

class TagAnnotation {
    rule : regexString
    groups : integer
    columns : list
    set_columns()
    get_columns()
    add_tags(text)
}

class FieldDescriptorAnnotation {
    origin : String
    description : String
    fields : Dict
    add_field(name, type, description)
    remove_field(name)
    get_field(name)
    to_json()
}

class ServiceExecutionAnnotation {
    service : String
    service_version : String
    user : String
    parameters : Dict
    to_yaml()
}

Metadata  |o..|{   Annotation
Annotation <|-- LabelAnnotation
Annotation <|-- TagAnnotation
Annotation <|-- FieldDescriptorAnnotation
FieldDescriptorAnnotation <|-- ServiceExecutionAnnotation
@enduml