---
name: build

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
    branches:
    - '**'
  schedule:
  # Build daily at 6:24am...
  - cron: '24 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r package-requirements.txt
    - name: Lint
      run: |
        pylint data_manager_metadata
        pyroma .
    - name: Test
      run: |
        python -m unittest test.test_metadata
        python -m unittest test.test_api
    - name: Build
      run: python setup.py bdist_wheel
